---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: documentation
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: documentation
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
